#!/usr/bin/env python3
"""generate_test_waveforms.py -- build the synthetic JHL fixture used by the
file-import tests.

WHY THIS EXISTS. PULSIM can read JCAMP-DX-style shape files, and that reader
needs testing. The real corpus this project works with (wave/) is vendor
material of uncertain licence and is excluded from the repository, which left
every file-import test skipping for anyone outside the group. This script
generates a waveform from a closed-form expression instead, so the parser and
the file-backed tutorials are reproducible from a clean clone.

The waveform is defined entirely by

    A_k   = sin(pi * k / (N - 1)) * 100      amplitude, percent, k = 0 .. N-1
    phi_k = 0                                phase, degrees

with N = 513. The count is odd on purpose: k = (N-1)/2 then lands exactly on
the peak, so the maximum is exactly 100 and the waveform is exactly symmetric,
which makes the fixture easy to check by eye and by assertion. Nothing here is derived from, measured against, or transcribed
from any vendor file: the expression, the point count, the field set, the title
and the comments are this project's own. Only the fields PULSIM's reader
actually requires are written, plus standard JCAMP-DX bookkeeping -- in
particular NO Bruker header keys, so the file parses to an empty header and the
shape falls back to area calibration, which is the behaviour we want to test.

Usage:
    python tools/generate_test_waveforms.py            # write the fixture
    python tools/generate_test_waveforms.py --check    # verify it is current
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parent.parent
FIXTURE = REPO / "tests" / "fixtures" / "waveforms" / "pulsim_sine.jhl"

N_POINTS = 513
AMPLITUDE_PERCENT = 100.0

PROVENANCE = (
    "This synthetic waveform was independently generated for testing PULSIM's",
    "JHL-compatible importer. It contains no waveform samples or metadata",
    "copied from Bruker or TopSpin files. Bruker and TopSpin are trademarks of",
    "their respective owner; this fixture is not affiliated with or endorsed by",
    "Bruker.",
)


def samples(n_points: int = N_POINTS):
    """A_k = sin(pi k / (N-1)) * 100, phi_k = 0.

    Half a sine cycle: the envelope starts and ends at exactly zero and, for an
    odd n_points, peaks at exactly AMPLITUDE_PERCENT on the centre sample."""
    k = np.arange(n_points, dtype=float)
    amplitude = np.sin(np.pi * k / (n_points - 1)) * AMPLITUDE_PERCENT
    phase = np.zeros(n_points, dtype=float)
    return amplitude, phase


def render(n_points: int = N_POINTS) -> str:
    """The fixture's exact text. Deterministic: same input, same bytes."""
    amplitude, phase = samples(n_points)
    lines = [
        "##TITLE= PULSIM synthetic sine test waveform",
        "##JCAMP-DX= 5.00 $$ JCAMP-DX is an IUPAC open specification",
        "##DATA TYPE= Shape Data Table",
        "##ORIGIN= PULSIM -- https://github.com/phillip-jaeslee/PULSIM",
        "##OWNER= PULSIM project, distributed under the repository's licence",
    ]
    lines += [f"$$ {line}" for line in PROVENANCE]
    lines += [
        "$$",
        "$$ Generated by tools/generate_test_waveforms.py. Do not hand-edit:",
        "$$ regenerate instead, and `--check` will confirm the file is current.",
        "$$",
        "$$ Definition, for k = 0 .. N-1 with N = "
        f"{n_points}:",
        f"$$     A_k   = sin(pi * k / (N - 1)) * {AMPLITUDE_PERCENT:g}   [percent]",
        "$$     phi_k = 0                                [degrees]",
        "$$",
        "$$ Columns below are amplitude, phase -- the only data PULSIM's",
        "$$ importer reads. No calibration or intent fields are present, so the",
        "$$ file parses to an empty header by design.",
        f"##NPOINTS= {n_points}",
        "##XYPOINTS= (XY..XY)",
    ]
    lines += [f"{a:.6e}, {p:.6e}" for a, p in zip(amplitude, phase)]
    lines.append("##END=")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed fixture differs")
    args = ap.parse_args()

    text = render()
    if args.check:
        if not FIXTURE.exists():
            print(f"missing: {FIXTURE.relative_to(REPO)}")
            return 1
        current = FIXTURE.read_text()
        if current != text:
            print(f"{FIXTURE.relative_to(REPO)} is not what the generator produces:")
            sys.stdout.writelines(difflib.unified_diff(
                current.splitlines(keepends=True), text.splitlines(keepends=True),
                fromfile="committed", tofile="generated", n=1))
            return 1
        print(f"{FIXTURE.relative_to(REPO)} is current ({N_POINTS} points)")
        return 0

    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(text)
    print(f"wrote {FIXTURE.relative_to(REPO)}  ({N_POINTS} points, "
          f"{FIXTURE.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
